# Github action that checks Python code quality.
# Action is fired on PR open against dev branch,
# when new commit is pushed against branch that
# has PR open to dev branch and on actual push
# to dev branch (if someone skips the PR process).

name: Run code quality checks
on:
  # pull_request_target:
  #   branches: [main]
  #   types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    name: Code quality check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This is necessary to get the commits
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python code checking dependencies
        run: pip install black pylint flake8 isort
      - name: Get changed python files between base and head
        run: >
          echo "CHANGED_FILES=$(echo $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} -- | grep \.py))" >> $GITHUB_ENV
      # - name: Get changed python files between base and head
      #   run: >
      #     echo "CHANGED_FILES=$(echo $(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- | grep \.py))" >> $GITHUB_ENV
      #- if: ${{ env.CHANGED_FILES }}
      - name: isort check
        id: isort-check
        #uses: marian-code/python-lint-annotate@v3
        # This runs various Python code checks and adds Github Action annotation.
        # See https://fusectore.dev/2021/11/19/github-action-problem-matchers.html
        run: |
          echo "::add-matcher::.github/workflows/matchers/isort.json"
          echo "::add-matcher::.github/workflows/matchers/isort_severity.json"
          isort --check-only --diff .
          echo "::remove-matcher owner=isort::"
          echo "::remove-matcher owner=isort_severity::"
        continue-on-error: true
      - name: black check
        id: black-check
        run: |
          echo "::add-matcher::.github/workflows/matchers/black.json"
          echo "::add-matcher::.github/workflows/matchers/black_severity.json"
          black --diff --check .
          echo "::remove-matcher owner=black::"
          echo "::remove-matcher owner=black_severity::"
        continue-on-error: true
      - name: Final status
        id: final-status
        if: steps.isort-check.outcome != 'success' || steps.black-check.outcome != 'success' #|| steps.pylint-check.outcome != 'success' || steps.flake8-check.outcome != 'success'
        run: |
          echo "::error::At least one check failed. Review annotations and logs for more info"
          exit 1
