# Github action that checks Python code quality.
# Action is fired on PR open against dev branch,
# when new commit is pushed against branch that
# has PR open to dev branch and on actual push
# to dev branch (if someone skips the PR process).

name: Run code quality checks
on:
  # pull_request_target:
  #   branches: [main]
  #   types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    name: Code quality check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This is necessary to get the commits
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get changed python files between base and head
        run: >
          echo "CHANGED_FILES=$(echo $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} -- | grep \.py))" >> $GITHUB_ENV
      - if: ${{ env.CHANGED_FILES }}
      - uses: marian-code/python-lint-annotate@v3
        with:
          #python-root-list: ${{ env.CHANGED_FILES }}
          #python-root-list: "."
          use-black: true
          use-isort: true
          use-pylint: true
          use-flake8: true
          use-mypy: false
          use-pycodestyle: false
          use-pydocstyle: false
          use-vulture: false
